# Generated by Django 4.1.5 on 2023-02-06 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
